/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model.impl;

import hr.crosig.proposal.model.InsuredRole;
import hr.crosig.proposal.service.InsuredRoleLocalServiceUtil;

/**
 * The extended model base implementation for the InsuredRole service. Represents a row in the &quot;AP_Proposal_InsuredRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InsuredRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InsuredRoleImpl
 * @see InsuredRole
 * @generated
 */
public abstract class InsuredRoleBaseImpl
	extends InsuredRoleModelImpl implements InsuredRole {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a insured role model instance should use the <code>InsuredRole</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			InsuredRoleLocalServiceUtil.addInsuredRole(this);
		}
		else {
			InsuredRoleLocalServiceUtil.updateInsuredRole(this);
		}
	}

}