/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import hr.crosig.proposal.model.InsuredRole;
import hr.crosig.proposal.model.InsuredRoleModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the InsuredRole service. Represents a row in the &quot;AP_Proposal_InsuredRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>InsuredRoleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InsuredRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InsuredRoleImpl
 * @generated
 */
public class InsuredRoleModelImpl
	extends BaseModelImpl<InsuredRole> implements InsuredRoleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a insured role model instance should use the <code>InsuredRole</code> interface instead.
	 */
	public static final String TABLE_NAME = "AP_Proposal_InsuredRole";

	public static final Object[][] TABLE_COLUMNS = {
		{"InsuredRoleId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"externalId", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("InsuredRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AP_Proposal_InsuredRole (InsuredRoleId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,name VARCHAR(75) null,externalId VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table AP_Proposal_InsuredRole";

	public static final String ORDER_BY_JPQL =
		" ORDER BY insuredRole.InsuredRoleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AP_Proposal_InsuredRole.InsuredRoleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INSUREDROLEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public InsuredRoleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _InsuredRoleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInsuredRoleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _InsuredRoleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return InsuredRole.class;
	}

	@Override
	public String getModelClassName() {
		return InsuredRole.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<InsuredRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<InsuredRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InsuredRole, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((InsuredRole)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<InsuredRole, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<InsuredRole, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(InsuredRole)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<InsuredRole, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<InsuredRole, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<InsuredRole, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<InsuredRole, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<InsuredRole, Object>>();

			attributeGetterFunctions.put(
				"InsuredRoleId", InsuredRole::getInsuredRoleId);
			attributeGetterFunctions.put(
				"companyId", InsuredRole::getCompanyId);
			attributeGetterFunctions.put("userId", InsuredRole::getUserId);
			attributeGetterFunctions.put("userName", InsuredRole::getUserName);
			attributeGetterFunctions.put(
				"createDate", InsuredRole::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", InsuredRole::getModifiedDate);
			attributeGetterFunctions.put("title", InsuredRole::getTitle);
			attributeGetterFunctions.put("name", InsuredRole::getName);
			attributeGetterFunctions.put(
				"externalId", InsuredRole::getExternalId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<InsuredRole, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<InsuredRole, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<InsuredRole, ?>>();

			attributeSetterBiConsumers.put(
				"InsuredRoleId",
				(BiConsumer<InsuredRole, Long>)InsuredRole::setInsuredRoleId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<InsuredRole, Long>)InsuredRole::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<InsuredRole, Long>)InsuredRole::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<InsuredRole, String>)InsuredRole::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<InsuredRole, Date>)InsuredRole::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<InsuredRole, Date>)InsuredRole::setModifiedDate);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<InsuredRole, String>)InsuredRole::setTitle);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<InsuredRole, String>)InsuredRole::setName);
			attributeSetterBiConsumers.put(
				"externalId",
				(BiConsumer<InsuredRole, String>)InsuredRole::setExternalId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getInsuredRoleId() {
		return _InsuredRoleId;
	}

	@Override
	public void setInsuredRoleId(long InsuredRoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_InsuredRoleId = InsuredRoleId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalInsuredRoleId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("InsuredRoleId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public String getExternalId() {
		if (_externalId == null) {
			return "";
		}
		else {
			return _externalId;
		}
	}

	@Override
	public void setExternalId(String externalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalId = externalId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), InsuredRole.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public InsuredRole toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, InsuredRole>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InsuredRoleImpl insuredRoleImpl = new InsuredRoleImpl();

		insuredRoleImpl.setInsuredRoleId(getInsuredRoleId());
		insuredRoleImpl.setCompanyId(getCompanyId());
		insuredRoleImpl.setUserId(getUserId());
		insuredRoleImpl.setUserName(getUserName());
		insuredRoleImpl.setCreateDate(getCreateDate());
		insuredRoleImpl.setModifiedDate(getModifiedDate());
		insuredRoleImpl.setTitle(getTitle());
		insuredRoleImpl.setName(getName());
		insuredRoleImpl.setExternalId(getExternalId());

		insuredRoleImpl.resetOriginalValues();

		return insuredRoleImpl;
	}

	@Override
	public InsuredRole cloneWithOriginalValues() {
		InsuredRoleImpl insuredRoleImpl = new InsuredRoleImpl();

		insuredRoleImpl.setInsuredRoleId(
			this.<Long>getColumnOriginalValue("InsuredRoleId"));
		insuredRoleImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		insuredRoleImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		insuredRoleImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		insuredRoleImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		insuredRoleImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		insuredRoleImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		insuredRoleImpl.setName(this.<String>getColumnOriginalValue("name"));
		insuredRoleImpl.setExternalId(
			this.<String>getColumnOriginalValue("externalId"));

		return insuredRoleImpl;
	}

	@Override
	public int compareTo(InsuredRole insuredRole) {
		long primaryKey = insuredRole.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof InsuredRole)) {
			return false;
		}

		InsuredRole insuredRole = (InsuredRole)object;

		long primaryKey = insuredRole.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<InsuredRole> toCacheModel() {
		InsuredRoleCacheModel insuredRoleCacheModel =
			new InsuredRoleCacheModel();

		insuredRoleCacheModel.InsuredRoleId = getInsuredRoleId();

		insuredRoleCacheModel.companyId = getCompanyId();

		insuredRoleCacheModel.userId = getUserId();

		insuredRoleCacheModel.userName = getUserName();

		String userName = insuredRoleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			insuredRoleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			insuredRoleCacheModel.createDate = createDate.getTime();
		}
		else {
			insuredRoleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			insuredRoleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			insuredRoleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		insuredRoleCacheModel.title = getTitle();

		String title = insuredRoleCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			insuredRoleCacheModel.title = null;
		}

		insuredRoleCacheModel.name = getName();

		String name = insuredRoleCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			insuredRoleCacheModel.name = null;
		}

		insuredRoleCacheModel.externalId = getExternalId();

		String externalId = insuredRoleCacheModel.externalId;

		if ((externalId != null) && (externalId.length() == 0)) {
			insuredRoleCacheModel.externalId = null;
		}

		return insuredRoleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<InsuredRole, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<InsuredRole, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<InsuredRole, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((InsuredRole)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, InsuredRole>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					InsuredRole.class, ModelWrapper.class);

	}

	private long _InsuredRoleId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _title;
	private String _name;
	private String _externalId;

	public <T> T getColumnValue(String columnName) {
		Function<InsuredRole, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((InsuredRole)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("InsuredRoleId", _InsuredRoleId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("externalId", _externalId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("InsuredRoleId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("userName", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("title", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("externalId", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private InsuredRole _escapedModel;

}