/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hr.crosig.proposal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import hr.crosig.proposal.model.PolicyCoverageOpt;
import hr.crosig.proposal.model.PolicyCoverageOptModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PolicyCoverageOpt service. Represents a row in the &quot;AP_Proposal_PolicyCoverageOpt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PolicyCoverageOptModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyCoverageOptImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolicyCoverageOptImpl
 * @generated
 */
public class PolicyCoverageOptModelImpl
	extends BaseModelImpl<PolicyCoverageOpt> implements PolicyCoverageOptModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy coverage opt model instance should use the <code>PolicyCoverageOpt</code> interface instead.
	 */
	public static final String TABLE_NAME = "AP_Proposal_PolicyCoverageOpt";

	public static final Object[][] TABLE_COLUMNS = {
		{"policyCoverageOptionId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"coverageOptionsName", Types.VARCHAR},
		{"coverageOptionsValue", Types.VARCHAR}, {"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("policyCoverageOptionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("coverageOptionsName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("coverageOptionsValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AP_Proposal_PolicyCoverageOpt (policyCoverageOptionId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,coverageOptionsName VARCHAR(75) null,coverageOptionsValue VARCHAR(75) null,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table AP_Proposal_PolicyCoverageOpt";

	public static final String ORDER_BY_JPQL =
		" ORDER BY policyCoverageOpt.policyCoverageOptionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AP_Proposal_PolicyCoverageOpt.policyCoverageOptionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long POLICYCOVERAGEOPTIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PolicyCoverageOptModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _policyCoverageOptionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPolicyCoverageOptionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _policyCoverageOptionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PolicyCoverageOpt.class;
	}

	@Override
	public String getModelClassName() {
		return PolicyCoverageOpt.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PolicyCoverageOpt, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PolicyCoverageOpt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolicyCoverageOpt, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PolicyCoverageOpt)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PolicyCoverageOpt, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PolicyCoverageOpt, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PolicyCoverageOpt)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PolicyCoverageOpt, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PolicyCoverageOpt, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PolicyCoverageOpt>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PolicyCoverageOpt.class.getClassLoader(), PolicyCoverageOpt.class,
			ModelWrapper.class);

		try {
			Constructor<PolicyCoverageOpt> constructor =
				(Constructor<PolicyCoverageOpt>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PolicyCoverageOpt, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PolicyCoverageOpt, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PolicyCoverageOpt, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PolicyCoverageOpt, Object>>();
		Map<String, BiConsumer<PolicyCoverageOpt, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<PolicyCoverageOpt, ?>>();

		attributeGetterFunctions.put(
			"policyCoverageOptionId",
			PolicyCoverageOpt::getPolicyCoverageOptionId);
		attributeSetterBiConsumers.put(
			"policyCoverageOptionId",
			(BiConsumer<PolicyCoverageOpt, Long>)
				PolicyCoverageOpt::setPolicyCoverageOptionId);
		attributeGetterFunctions.put(
			"companyId", PolicyCoverageOpt::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PolicyCoverageOpt, Long>)
				PolicyCoverageOpt::setCompanyId);
		attributeGetterFunctions.put("userId", PolicyCoverageOpt::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<PolicyCoverageOpt, Long>)PolicyCoverageOpt::setUserId);
		attributeGetterFunctions.put(
			"userName", PolicyCoverageOpt::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<PolicyCoverageOpt, String>)
				PolicyCoverageOpt::setUserName);
		attributeGetterFunctions.put(
			"createDate", PolicyCoverageOpt::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<PolicyCoverageOpt, Date>)
				PolicyCoverageOpt::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", PolicyCoverageOpt::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<PolicyCoverageOpt, Date>)
				PolicyCoverageOpt::setModifiedDate);
		attributeGetterFunctions.put(
			"coverageOptionsName", PolicyCoverageOpt::getCoverageOptionsName);
		attributeSetterBiConsumers.put(
			"coverageOptionsName",
			(BiConsumer<PolicyCoverageOpt, String>)
				PolicyCoverageOpt::setCoverageOptionsName);
		attributeGetterFunctions.put(
			"coverageOptionsValue", PolicyCoverageOpt::getCoverageOptionsValue);
		attributeSetterBiConsumers.put(
			"coverageOptionsValue",
			(BiConsumer<PolicyCoverageOpt, String>)
				PolicyCoverageOpt::setCoverageOptionsValue);
		attributeGetterFunctions.put("type", PolicyCoverageOpt::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<PolicyCoverageOpt, String>)PolicyCoverageOpt::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getPolicyCoverageOptionId() {
		return _policyCoverageOptionId;
	}

	@Override
	public void setPolicyCoverageOptionId(long policyCoverageOptionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_policyCoverageOptionId = policyCoverageOptionId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getCoverageOptionsName() {
		if (_coverageOptionsName == null) {
			return "";
		}
		else {
			return _coverageOptionsName;
		}
	}

	@Override
	public void setCoverageOptionsName(String coverageOptionsName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_coverageOptionsName = coverageOptionsName;
	}

	@Override
	public String getCoverageOptionsValue() {
		if (_coverageOptionsValue == null) {
			return "";
		}
		else {
			return _coverageOptionsValue;
		}
	}

	@Override
	public void setCoverageOptionsValue(String coverageOptionsValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_coverageOptionsValue = coverageOptionsValue;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PolicyCoverageOpt.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PolicyCoverageOpt toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PolicyCoverageOpt>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolicyCoverageOptImpl policyCoverageOptImpl =
			new PolicyCoverageOptImpl();

		policyCoverageOptImpl.setPolicyCoverageOptionId(
			getPolicyCoverageOptionId());
		policyCoverageOptImpl.setCompanyId(getCompanyId());
		policyCoverageOptImpl.setUserId(getUserId());
		policyCoverageOptImpl.setUserName(getUserName());
		policyCoverageOptImpl.setCreateDate(getCreateDate());
		policyCoverageOptImpl.setModifiedDate(getModifiedDate());
		policyCoverageOptImpl.setCoverageOptionsName(getCoverageOptionsName());
		policyCoverageOptImpl.setCoverageOptionsValue(
			getCoverageOptionsValue());
		policyCoverageOptImpl.setType(getType());

		policyCoverageOptImpl.resetOriginalValues();

		return policyCoverageOptImpl;
	}

	@Override
	public int compareTo(PolicyCoverageOpt policyCoverageOpt) {
		long primaryKey = policyCoverageOpt.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PolicyCoverageOpt)) {
			return false;
		}

		PolicyCoverageOpt policyCoverageOpt = (PolicyCoverageOpt)object;

		long primaryKey = policyCoverageOpt.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PolicyCoverageOpt> toCacheModel() {
		PolicyCoverageOptCacheModel policyCoverageOptCacheModel =
			new PolicyCoverageOptCacheModel();

		policyCoverageOptCacheModel.policyCoverageOptionId =
			getPolicyCoverageOptionId();

		policyCoverageOptCacheModel.companyId = getCompanyId();

		policyCoverageOptCacheModel.userId = getUserId();

		policyCoverageOptCacheModel.userName = getUserName();

		String userName = policyCoverageOptCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			policyCoverageOptCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			policyCoverageOptCacheModel.createDate = createDate.getTime();
		}
		else {
			policyCoverageOptCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			policyCoverageOptCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			policyCoverageOptCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		policyCoverageOptCacheModel.coverageOptionsName =
			getCoverageOptionsName();

		String coverageOptionsName =
			policyCoverageOptCacheModel.coverageOptionsName;

		if ((coverageOptionsName != null) &&
			(coverageOptionsName.length() == 0)) {

			policyCoverageOptCacheModel.coverageOptionsName = null;
		}

		policyCoverageOptCacheModel.coverageOptionsValue =
			getCoverageOptionsValue();

		String coverageOptionsValue =
			policyCoverageOptCacheModel.coverageOptionsValue;

		if ((coverageOptionsValue != null) &&
			(coverageOptionsValue.length() == 0)) {

			policyCoverageOptCacheModel.coverageOptionsValue = null;
		}

		policyCoverageOptCacheModel.type = getType();

		String type = policyCoverageOptCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			policyCoverageOptCacheModel.type = null;
		}

		return policyCoverageOptCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PolicyCoverageOpt, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PolicyCoverageOpt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolicyCoverageOpt, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PolicyCoverageOpt)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PolicyCoverageOpt, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PolicyCoverageOpt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PolicyCoverageOpt, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PolicyCoverageOpt)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PolicyCoverageOpt>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _policyCoverageOptionId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _coverageOptionsName;
	private String _coverageOptionsValue;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PolicyCoverageOpt, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PolicyCoverageOpt)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"policyCoverageOptionId", _policyCoverageOptionId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("coverageOptionsName", _coverageOptionsName);
		_columnOriginalValues.put(
			"coverageOptionsValue", _coverageOptionsValue);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("policyCoverageOptionId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("userName", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("coverageOptionsName", 64L);

		columnBitmasks.put("coverageOptionsValue", 128L);

		columnBitmasks.put("type_", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PolicyCoverageOpt _escapedModel;

}