/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model.impl;

import hr.crosig.proposal.model.PolicyCoverageOpt;
import hr.crosig.proposal.service.PolicyCoverageOptLocalServiceUtil;

/**
 * The extended model base implementation for the PolicyCoverageOpt service. Represents a row in the &quot;AP_Proposal_PolicyCoverageOpt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolicyCoverageOptImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolicyCoverageOptImpl
 * @see PolicyCoverageOpt
 * @generated
 */
public abstract class PolicyCoverageOptBaseImpl
	extends PolicyCoverageOptModelImpl implements PolicyCoverageOpt {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a policy coverage opt model instance should use the <code>PolicyCoverageOpt</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PolicyCoverageOptLocalServiceUtil.addPolicyCoverageOpt(this);
		}
		else {
			PolicyCoverageOptLocalServiceUtil.updatePolicyCoverageOpt(this);
		}
	}

}