/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model.impl;

import hr.crosig.proposal.model.ProductRole;
import hr.crosig.proposal.service.ProductRoleLocalServiceUtil;

/**
 * The extended model base implementation for the ProductRole service. Represents a row in the &quot;AP_Proposal_ProductRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductRoleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductRoleImpl
 * @see ProductRole
 * @generated
 */
public abstract class ProductRoleBaseImpl
	extends ProductRoleModelImpl implements ProductRole {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product role model instance should use the <code>ProductRole</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProductRoleLocalServiceUtil.addProductRole(this);
		}
		else {
			ProductRoleLocalServiceUtil.updateProductRole(this);
		}
	}

}