/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model.impl;

import hr.crosig.proposal.model.Proposal;
import hr.crosig.proposal.service.ProposalLocalServiceUtil;

/**
 * The extended model base implementation for the Proposal service. Represents a row in the &quot;AP_Proposal_Proposal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProposalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProposalImpl
 * @see Proposal
 * @generated
 */
public abstract class ProposalBaseImpl
	extends ProposalModelImpl implements Proposal {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a proposal model instance should use the <code>Proposal</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProposalLocalServiceUtil.addProposal(this);
		}
		else {
			ProposalLocalServiceUtil.updateProposal(this);
		}
	}

}