/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model.impl;

import hr.crosig.proposal.model.ProposalContact;
import hr.crosig.proposal.service.ProposalContactLocalServiceUtil;

/**
 * The extended model base implementation for the ProposalContact service. Represents a row in the &quot;AP_Proposal_ProposalContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProposalContactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProposalContactImpl
 * @see ProposalContact
 * @generated
 */
public abstract class ProposalContactBaseImpl
	extends ProposalContactModelImpl implements ProposalContact {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a proposal contact model instance should use the <code>ProposalContact</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProposalContactLocalServiceUtil.addProposalContact(this);
		}
		else {
			ProposalContactLocalServiceUtil.updateProposalContact(this);
		}
	}

}