/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Street service. Represents a row in the &quot;AP_Contact_Street&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hr.crosig.contact.model.impl.StreetModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hr.crosig.contact.model.impl.StreetImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Street
 * @generated
 */
@ProviderType
public interface StreetModel
	extends AuditedModel, BaseModel<Street>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a street model instance should use the {@link Street} interface instead.
	 */

	/**
	 * Returns the primary key of this street.
	 *
	 * @return the primary key of this street
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this street.
	 *
	 * @param primaryKey the primary key of this street
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the street ID of this street.
	 *
	 * @return the street ID of this street
	 */
	public long getStreetId();

	/**
	 * Sets the street ID of this street.
	 *
	 * @param streetId the street ID of this street
	 */
	public void setStreetId(long streetId);

	/**
	 * Returns the company ID of this street.
	 *
	 * @return the company ID of this street
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this street.
	 *
	 * @param companyId the company ID of this street
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this street.
	 *
	 * @return the user ID of this street
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this street.
	 *
	 * @param userId the user ID of this street
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this street.
	 *
	 * @return the user uuid of this street
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this street.
	 *
	 * @param userUuid the user uuid of this street
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this street.
	 *
	 * @return the user name of this street
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this street.
	 *
	 * @param userName the user name of this street
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this street.
	 *
	 * @return the create date of this street
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this street.
	 *
	 * @param createDate the create date of this street
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this street.
	 *
	 * @return the modified date of this street
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this street.
	 *
	 * @param modifiedDate the modified date of this street
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external ID of this street.
	 *
	 * @return the external ID of this street
	 */
	public long getExternalId();

	/**
	 * Sets the external ID of this street.
	 *
	 * @param externalId the external ID of this street
	 */
	public void setExternalId(long externalId);

	/**
	 * Returns the name of this street.
	 *
	 * @return the name of this street
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this street.
	 *
	 * @param name the name of this street
	 */
	public void setName(String name);

	/**
	 * Returns the city ID of this street.
	 *
	 * @return the city ID of this street
	 */
	public long getCityId();

	/**
	 * Sets the city ID of this street.
	 *
	 * @param cityId the city ID of this street
	 */
	public void setCityId(long cityId);

	@Override
	public Street cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}