/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hr.crosig.proposal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InsuredRole service. Represents a row in the &quot;AP_Proposal_InsuredRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hr.crosig.proposal.model.impl.InsuredRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hr.crosig.proposal.model.impl.InsuredRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InsuredRole
 * @generated
 */
@ProviderType
public interface InsuredRoleModel extends BaseModel<InsuredRole> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a insured role model instance should use the {@link InsuredRole} interface instead.
	 */

	/**
	 * Returns the primary key of this insured role.
	 *
	 * @return the primary key of this insured role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insured role.
	 *
	 * @param primaryKey the primary key of this insured role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the insured role ID of this insured role.
	 *
	 * @return the insured role ID of this insured role
	 */
	public long getInsuredRoleId();

	/**
	 * Sets the insured role ID of this insured role.
	 *
	 * @param InsuredRoleId the insured role ID of this insured role
	 */
	public void setInsuredRoleId(long InsuredRoleId);

	/**
	 * Returns the title of this insured role.
	 *
	 * @return the title of this insured role
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this insured role.
	 *
	 * @param title the title of this insured role
	 */
	public void setTitle(String title);

	/**
	 * Returns the name of this insured role.
	 *
	 * @return the name of this insured role
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this insured role.
	 *
	 * @param name the name of this insured role
	 */
	public void setName(String name);

	/**
	 * Returns the external ID of this insured role.
	 *
	 * @return the external ID of this insured role
	 */
	@AutoEscape
	public String getExternalId();

	/**
	 * Sets the external ID of this insured role.
	 *
	 * @param externalId the external ID of this insured role
	 */
	public void setExternalId(String externalId);

}