/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the InsuredRole service. Represents a row in the &quot;AP_Proposal_InsuredRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hr.crosig.proposal.model.impl.InsuredRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hr.crosig.proposal.model.impl.InsuredRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InsuredRole
 * @generated
 */
@ProviderType
public interface InsuredRoleModel
	extends AuditedModel, BaseModel<InsuredRole>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a insured role model instance should use the {@link InsuredRole} interface instead.
	 */

	/**
	 * Returns the primary key of this insured role.
	 *
	 * @return the primary key of this insured role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this insured role.
	 *
	 * @param primaryKey the primary key of this insured role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the insured role ID of this insured role.
	 *
	 * @return the insured role ID of this insured role
	 */
	public long getInsuredRoleId();

	/**
	 * Sets the insured role ID of this insured role.
	 *
	 * @param InsuredRoleId the insured role ID of this insured role
	 */
	public void setInsuredRoleId(long InsuredRoleId);

	/**
	 * Returns the company ID of this insured role.
	 *
	 * @return the company ID of this insured role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this insured role.
	 *
	 * @param companyId the company ID of this insured role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this insured role.
	 *
	 * @return the user ID of this insured role
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this insured role.
	 *
	 * @param userId the user ID of this insured role
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this insured role.
	 *
	 * @return the user uuid of this insured role
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this insured role.
	 *
	 * @param userUuid the user uuid of this insured role
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this insured role.
	 *
	 * @return the user name of this insured role
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this insured role.
	 *
	 * @param userName the user name of this insured role
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this insured role.
	 *
	 * @return the create date of this insured role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this insured role.
	 *
	 * @param createDate the create date of this insured role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this insured role.
	 *
	 * @return the modified date of this insured role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this insured role.
	 *
	 * @param modifiedDate the modified date of this insured role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this insured role.
	 *
	 * @return the title of this insured role
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this insured role.
	 *
	 * @param title the title of this insured role
	 */
	public void setTitle(String title);

	/**
	 * Returns the name of this insured role.
	 *
	 * @return the name of this insured role
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this insured role.
	 *
	 * @param name the name of this insured role
	 */
	public void setName(String name);

	/**
	 * Returns the external ID of this insured role.
	 *
	 * @return the external ID of this insured role
	 */
	@AutoEscape
	public String getExternalId();

	/**
	 * Sets the external ID of this insured role.
	 *
	 * @param externalId the external ID of this insured role
	 */
	public void setExternalId(String externalId);

	@Override
	public InsuredRole cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}