/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hr.crosig.proposal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PolicyCoverageOpt service. Represents a row in the &quot;AP_Proposal_PolicyCoverageOpt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hr.crosig.proposal.model.impl.PolicyCoverageOptModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hr.crosig.proposal.model.impl.PolicyCoverageOptImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolicyCoverageOpt
 * @generated
 */
@ProviderType
public interface PolicyCoverageOptModel
	extends AuditedModel, BaseModel<PolicyCoverageOpt>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a policy coverage opt model instance should use the {@link PolicyCoverageOpt} interface instead.
	 */

	/**
	 * Returns the primary key of this policy coverage opt.
	 *
	 * @return the primary key of this policy coverage opt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this policy coverage opt.
	 *
	 * @param primaryKey the primary key of this policy coverage opt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the policy coverage option ID of this policy coverage opt.
	 *
	 * @return the policy coverage option ID of this policy coverage opt
	 */
	public long getPolicyCoverageOptionId();

	/**
	 * Sets the policy coverage option ID of this policy coverage opt.
	 *
	 * @param policyCoverageOptionId the policy coverage option ID of this policy coverage opt
	 */
	public void setPolicyCoverageOptionId(long policyCoverageOptionId);

	/**
	 * Returns the company ID of this policy coverage opt.
	 *
	 * @return the company ID of this policy coverage opt
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this policy coverage opt.
	 *
	 * @param companyId the company ID of this policy coverage opt
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this policy coverage opt.
	 *
	 * @return the user ID of this policy coverage opt
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this policy coverage opt.
	 *
	 * @param userId the user ID of this policy coverage opt
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this policy coverage opt.
	 *
	 * @return the user uuid of this policy coverage opt
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this policy coverage opt.
	 *
	 * @param userUuid the user uuid of this policy coverage opt
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this policy coverage opt.
	 *
	 * @return the user name of this policy coverage opt
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this policy coverage opt.
	 *
	 * @param userName the user name of this policy coverage opt
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this policy coverage opt.
	 *
	 * @return the create date of this policy coverage opt
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this policy coverage opt.
	 *
	 * @param createDate the create date of this policy coverage opt
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this policy coverage opt.
	 *
	 * @return the modified date of this policy coverage opt
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this policy coverage opt.
	 *
	 * @param modifiedDate the modified date of this policy coverage opt
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the proposal ID of this policy coverage opt.
	 *
	 * @return the proposal ID of this policy coverage opt
	 */
	public long getProposalId();

	/**
	 * Sets the proposal ID of this policy coverage opt.
	 *
	 * @param proposalId the proposal ID of this policy coverage opt
	 */
	public void setProposalId(long proposalId);

	/**
	 * Returns the coverage options name of this policy coverage opt.
	 *
	 * @return the coverage options name of this policy coverage opt
	 */
	@AutoEscape
	public String getCoverageOptionsName();

	/**
	 * Sets the coverage options name of this policy coverage opt.
	 *
	 * @param coverageOptionsName the coverage options name of this policy coverage opt
	 */
	public void setCoverageOptionsName(String coverageOptionsName);

	/**
	 * Returns the coverage options value of this policy coverage opt.
	 *
	 * @return the coverage options value of this policy coverage opt
	 */
	@AutoEscape
	public String getCoverageOptionsValue();

	/**
	 * Sets the coverage options value of this policy coverage opt.
	 *
	 * @param coverageOptionsValue the coverage options value of this policy coverage opt
	 */
	public void setCoverageOptionsValue(String coverageOptionsValue);

	/**
	 * Returns the type of this policy coverage opt.
	 *
	 * @return the type of this policy coverage opt
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this policy coverage opt.
	 *
	 * @param type the type of this policy coverage opt
	 */
	public void setType(String type);

}