/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hr.crosig.proposal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductRole service. Represents a row in the &quot;AP_Proposal_ProductRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hr.crosig.proposal.model.impl.ProductRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hr.crosig.proposal.model.impl.ProductRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductRole
 * @generated
 */
@ProviderType
public interface ProductRoleModel
	extends AuditedModel, BaseModel<ProductRole>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product role model instance should use the {@link ProductRole} interface instead.
	 */

	/**
	 * Returns the primary key of this product role.
	 *
	 * @return the primary key of this product role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product role.
	 *
	 * @param primaryKey the primary key of this product role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product role ID of this product role.
	 *
	 * @return the product role ID of this product role
	 */
	public long getProductRoleId();

	/**
	 * Sets the product role ID of this product role.
	 *
	 * @param productRoleId the product role ID of this product role
	 */
	public void setProductRoleId(long productRoleId);

	/**
	 * Returns the company ID of this product role.
	 *
	 * @return the company ID of this product role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product role.
	 *
	 * @param companyId the company ID of this product role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product role.
	 *
	 * @return the user ID of this product role
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product role.
	 *
	 * @param userId the user ID of this product role
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product role.
	 *
	 * @return the user uuid of this product role
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product role.
	 *
	 * @param userUuid the user uuid of this product role
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product role.
	 *
	 * @return the user name of this product role
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product role.
	 *
	 * @param userName the user name of this product role
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this product role.
	 *
	 * @return the create date of this product role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product role.
	 *
	 * @param createDate the create date of this product role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product role.
	 *
	 * @return the modified date of this product role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product role.
	 *
	 * @param modifiedDate the modified date of this product role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the product ID of this product role.
	 *
	 * @return the product ID of this product role
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product role.
	 *
	 * @param productId the product ID of this product role
	 */
	public void setProductId(long productId);

	/**
	 * Returns the role ID of this product role.
	 *
	 * @return the role ID of this product role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this product role.
	 *
	 * @param roleId the role ID of this product role
	 */
	public void setRoleId(long roleId);

}