/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.proposal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProposalContact service. Represents a row in the &quot;AP_Proposal_ProposalContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hr.crosig.proposal.model.impl.ProposalContactModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hr.crosig.proposal.model.impl.ProposalContactImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProposalContact
 * @generated
 */
@ProviderType
public interface ProposalContactModel
	extends AuditedModel, BaseModel<ProposalContact>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proposal contact model instance should use the {@link ProposalContact} interface instead.
	 */

	/**
	 * Returns the primary key of this proposal contact.
	 *
	 * @return the primary key of this proposal contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proposal contact.
	 *
	 * @param primaryKey the primary key of this proposal contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the proposal contact ID of this proposal contact.
	 *
	 * @return the proposal contact ID of this proposal contact
	 */
	public long getProposalContactId();

	/**
	 * Sets the proposal contact ID of this proposal contact.
	 *
	 * @param proposalContactId the proposal contact ID of this proposal contact
	 */
	public void setProposalContactId(long proposalContactId);

	/**
	 * Returns the company ID of this proposal contact.
	 *
	 * @return the company ID of this proposal contact
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this proposal contact.
	 *
	 * @param companyId the company ID of this proposal contact
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this proposal contact.
	 *
	 * @return the user ID of this proposal contact
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this proposal contact.
	 *
	 * @param userId the user ID of this proposal contact
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this proposal contact.
	 *
	 * @return the user uuid of this proposal contact
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this proposal contact.
	 *
	 * @param userUuid the user uuid of this proposal contact
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this proposal contact.
	 *
	 * @return the user name of this proposal contact
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this proposal contact.
	 *
	 * @param userName the user name of this proposal contact
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this proposal contact.
	 *
	 * @return the create date of this proposal contact
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this proposal contact.
	 *
	 * @param createDate the create date of this proposal contact
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this proposal contact.
	 *
	 * @return the modified date of this proposal contact
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this proposal contact.
	 *
	 * @param modifiedDate the modified date of this proposal contact
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the proposal ID of this proposal contact.
	 *
	 * @return the proposal ID of this proposal contact
	 */
	public long getProposalId();

	/**
	 * Sets the proposal ID of this proposal contact.
	 *
	 * @param proposalId the proposal ID of this proposal contact
	 */
	public void setProposalId(long proposalId);

	/**
	 * Returns the contact ext number of this proposal contact.
	 *
	 * @return the contact ext number of this proposal contact
	 */
	@AutoEscape
	public String getContactExtNumber();

	/**
	 * Sets the contact ext number of this proposal contact.
	 *
	 * @param contactExtNumber the contact ext number of this proposal contact
	 */
	public void setContactExtNumber(String contactExtNumber);

	/**
	 * Returns the insured roles of this proposal contact.
	 *
	 * @return the insured roles of this proposal contact
	 */
	@AutoEscape
	public String getInsuredRoles();

	/**
	 * Sets the insured roles of this proposal contact.
	 *
	 * @param insuredRoles the insured roles of this proposal contact
	 */
	public void setInsuredRoles(String insuredRoles);

	@Override
	public ProposalContact cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}