/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package hr.crosig.proposal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Proposal service. Represents a row in the &quot;AP_Proposal_Proposal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>hr.crosig.proposal.model.impl.ProposalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>hr.crosig.proposal.model.impl.ProposalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Proposal
 * @generated
 */
@ProviderType
public interface ProposalModel
	extends AuditedModel, BaseModel<Proposal>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proposal model instance should use the {@link Proposal} interface instead.
	 */

	/**
	 * Returns the primary key of this proposal.
	 *
	 * @return the primary key of this proposal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proposal.
	 *
	 * @param primaryKey the primary key of this proposal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the proposal ID of this proposal.
	 *
	 * @return the proposal ID of this proposal
	 */
	public long getProposalId();

	/**
	 * Sets the proposal ID of this proposal.
	 *
	 * @param proposalId the proposal ID of this proposal
	 */
	public void setProposalId(long proposalId);

	/**
	 * Returns the company ID of this proposal.
	 *
	 * @return the company ID of this proposal
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this proposal.
	 *
	 * @param companyId the company ID of this proposal
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this proposal.
	 *
	 * @return the user ID of this proposal
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this proposal.
	 *
	 * @param userId the user ID of this proposal
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this proposal.
	 *
	 * @return the user uuid of this proposal
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this proposal.
	 *
	 * @param userUuid the user uuid of this proposal
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this proposal.
	 *
	 * @return the user name of this proposal
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this proposal.
	 *
	 * @param userName the user name of this proposal
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this proposal.
	 *
	 * @return the create date of this proposal
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this proposal.
	 *
	 * @param createDate the create date of this proposal
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this proposal.
	 *
	 * @return the modified date of this proposal
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this proposal.
	 *
	 * @param modifiedDate the modified date of this proposal
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the external proposal number of this proposal.
	 *
	 * @return the external proposal number of this proposal
	 */
	@AutoEscape
	public String getExternalProposalNumber();

	/**
	 * Sets the external proposal number of this proposal.
	 *
	 * @param externalProposalNumber the external proposal number of this proposal
	 */
	public void setExternalProposalNumber(String externalProposalNumber);

	/**
	 * Returns the last update of this proposal.
	 *
	 * @return the last update of this proposal
	 */
	public Date getLastUpdate();

	/**
	 * Sets the last update of this proposal.
	 *
	 * @param lastUpdate the last update of this proposal
	 */
	public void setLastUpdate(Date lastUpdate);

	/**
	 * Returns the origin of this proposal.
	 *
	 * @return the origin of this proposal
	 */
	@AutoEscape
	public String getOrigin();

	/**
	 * Sets the origin of this proposal.
	 *
	 * @param origin the origin of this proposal
	 */
	public void setOrigin(String origin);

	/**
	 * Returns the agent user ID of this proposal.
	 *
	 * @return the agent user ID of this proposal
	 */
	public long getAgentUserId();

	/**
	 * Sets the agent user ID of this proposal.
	 *
	 * @param agentUserId the agent user ID of this proposal
	 */
	public void setAgentUserId(long agentUserId);

	/**
	 * Returns the agent user uuid of this proposal.
	 *
	 * @return the agent user uuid of this proposal
	 */
	public String getAgentUserUuid();

	/**
	 * Sets the agent user uuid of this proposal.
	 *
	 * @param agentUserUuid the agent user uuid of this proposal
	 */
	public void setAgentUserUuid(String agentUserUuid);

	/**
	 * Returns the policy holder ext number of this proposal.
	 *
	 * @return the policy holder ext number of this proposal
	 */
	@AutoEscape
	public String getPolicyHolderExtNumber();

	/**
	 * Sets the policy holder ext number of this proposal.
	 *
	 * @param policyHolderExtNumber the policy holder ext number of this proposal
	 */
	public void setPolicyHolderExtNumber(String policyHolderExtNumber);

	/**
	 * Returns the insured object ext number of this proposal.
	 *
	 * @return the insured object ext number of this proposal
	 */
	@AutoEscape
	public String getInsuredObjectExtNumber();

	/**
	 * Sets the insured object ext number of this proposal.
	 *
	 * @param insuredObjectExtNumber the insured object ext number of this proposal
	 */
	public void setInsuredObjectExtNumber(String insuredObjectExtNumber);

	/**
	 * Returns the status of this proposal.
	 *
	 * @return the status of this proposal
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this proposal.
	 *
	 * @param status the status of this proposal
	 */
	public void setStatus(String status);

}