/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package hr.crosig.contact.model.impl;

import hr.crosig.contact.model.City;
import hr.crosig.contact.service.CityLocalServiceUtil;

/**
 * The extended model base implementation for the City service. Represents a row in the &quot;AP_Contact_City&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CityImpl
 * @see City
 * @generated
 */
public abstract class CityBaseImpl extends CityModelImpl implements City {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a city model instance should use the <code>City</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CityLocalServiceUtil.addCity(this);
		}
		else {
			CityLocalServiceUtil.updateCity(this);
		}
	}

}